version: '3.5'

services:
  ftt-db:
    image: postgres:14.3-alpine3.16
    restart: always
    container_name: dev-ftt-db
    environment:
      POSTGRES_DB: "dev_ftt_db"
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev_password'
      ELASTIC_ADDRESS: elasticsearch
      ELASTIC_PORT: 9200
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch_dev
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
