version: '3.5'

services:
  ftt-db:
    image: postgres:14.3-alpine3.16
    restart: always
    container_name: dev-ftt-db
    environment:
      POSTGRES_DB: "dev_ftt_db"
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev_password'
    ports:
      - "5432:5432"

