CREATE TABLE IF NOT EXISTS locale_config (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country varchar(100) NOT NULL ,
    market varchar(100) NOT NULL ,
    locale varchar(100) NOT NULL,
    currency varchar(100) NOT NULL,
    site varchar(100) NOT NULL
);

ALTER TABLE tg_user
    ADD COLUMN market varchar(100),
    ADD COLUMN locale varchar(100),
    ADD COLUMN currency varchar(100);