CREATE TABLE IF NOT EXISTS airport (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata varchar(200) NOT NULL ,
    icao varchar(200) NOT NULL ,
    airport_name varchar(200) NOT NULL,
    location varchar(200) NOT NULL,
    utc_time varchar(200) NOT NULL,
    sky_id varchar(200) NOT NULL
    );