# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up postgresSQL
    - uses: harmon758/postgresql-action@v1.1
      with:
        postgresql version: '14.3-alpine3.16'
        postgresql database: 'dev_ftt_db'
        postgresql user: 'test'
        postgresql password: 'test_password'
        run: mvn -B package --file pom.xml
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
    - name: Build with Maven
      env:
        TELEGRAM_NAME: ${{secrets.TELEGRAM_NAME}}
        TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
      run: mvn -B package --file pom.xml
